export enum Rol {
  CLIENTE = "CLIENTE",
  PROFESIONAL = "PROFESIONAL",
  ADMIN = "ADMIN",
}

export enum EstadoTrabajo {
  PENDIENTE = "PENDIENTE",
  ASIGNADO = "ASIGNADO",
  PENDIENTE_CONFIRMACION = "PENDIENTE_CONFIRMACION",
  FINALIZADO = "FINALIZADO",
  CANCELADO = "CANCELADO",
  EN_RECLAMO = "EN_RECLAMO",
}

export enum EstadoPago {
  PENDIENTE = "PENDIENTE",
  COMPLETADO = "COMPLETADO",
  FALLIDO = "FALLIDO",
}

export enum TipoNotificacion {
  OFERTA_ACEPTADA = "OFERTA_ACEPTADA",
  NUEVO_MENSAJE = "NUEVO_MENSAJE",
  TRABAJO_FINALIZADO = "TRABAJO_FINALIZADO",
  SUSCRIPCION_POR_VENCER = "SUSCRIPCION_POR_VENCER",
}

export enum NivelSuscripcion {
  BASICO = "BASICO",
  PREMIUM = "PREMIUM",
}

export enum EstadoVerificacion {
  PENDIENTE = "PENDIENTE",
  APROBADA = "APROBADA",
  RECHAZADA = "RECHAZADA",
}
  