import { StyleSheet } from "react-native";

export const dashboardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#E6EDF6",
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 34,
    paddingBottom: 50,
    gap: 20,
  },
  header: {
    marginBottom: 2,
    backgroundColor: "#C7DBFF",
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 18,
    borderWidth: 1,
    borderColor: "#AFC9F9",
  },
  headerKicker: {
    fontSize: 12,
    fontWeight: "700",
    color: "#27538D",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  headerTitle: {
    marginTop: 8,
    fontSize: 28,
    fontWeight: "800",
    color: "#0F2A52",
  },
  headerSubtitle: {
    marginTop: 8,
    color: "#3D628F",
    lineHeight: 20,
  },
  ctaMain: {
    backgroundColor: "#2563EB",
    borderRadius: 18,
    paddingHorizontal: 22,
    paddingVertical: 22,
    shadowColor: "#0F172A",
    shadowOpacity: 0.2,
    shadowRadius: 18,
    elevation: 6,
  },
  ctaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  ctaMainTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "700",
  },
  ctaMainText: {
    marginTop: 7,
    color: "#DBEAFE",
    fontSize: 14,
  },
  pendingCard: {
    backgroundColor: "#F9F3E3",
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: "#E8D4A8",
    shadowColor: "#0F172A",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  pendingCardNeutral: {
    backgroundColor: "#EEF2FF",
    borderColor: "#CBD5F5",
    shadowColor: "#0F172A",
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 6,
  },
  pendingTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#92400E",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  pendingTitleNeutral: {
    color: "#1E3A8A",
  },
  pendingText: {
    marginTop: 4,
    color: "#B45309",
    fontWeight: "700",
  },
  pendingEmptyText: {
    marginTop: 4,
    color: "#8A5A00",
    fontWeight: "600",
  },
  locationWarningCard: {
    backgroundColor: "#E8F0FF",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#BFD8FF",
    shadowColor: "#2563EB",
    shadowOpacity: 0.14,
    shadowRadius: 12,
    elevation: 3,
  },
  locationWarningTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#1E3A8A",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  locationWarningText: {
    marginTop: 5,
    color: "#365D8F",
    fontWeight: "600",
  },
  grid: {
    flexDirection: "row",
    gap: 12,
  },
  listCard: {
    borderRadius: 18,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "#D7DEE9",
    backgroundColor: "#FFFFFF",
    shadowColor: "#0F172A",
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 2,
  },
  listItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  listLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  listTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#10386E",
  },
  listSubtitle: {
    marginTop: 2,
    color: "#64748B",
    fontSize: 12,
  },
  divider: {
    height: 1,
    backgroundColor: "#E2E8F0",
    marginHorizontal: 18,
  },
  logoutLink: {
    marginTop: 12,
    alignItems: "center",
  },
  logoutText: {
    color: "#B42318",
    fontWeight: "700",
  },
});
