import { StyleSheet } from "react-native";
import { RADIUS, SPACING } from "../theme";

export const perfilClienteStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#EAF2FF",
  },
  content: {
    paddingTop: 30,
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.lg,
    gap: SPACING.md,
  },
  heroCard: {
    backgroundColor: "#C7DBFF",
    borderColor: "#AFC9F9",
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
    shadowColor: "#2563EB",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  heroKicker: {
    fontSize: 11,
    fontWeight: "800",
    color: "#27538D",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  heroTitle: {
    marginTop: 4,
    fontSize: 22,
    fontWeight: "800",
    color: "#0F2A52",
  },
  heroSubtitle: {
    marginTop: 4,
    color: "#3F628E",
    fontWeight: "600",
  },
  heroMetaRow: {
    marginTop: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  heroPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#EDF5FF",
    borderWidth: 1,
    borderColor: "#C8DCFF",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  heroPillText: {
    color: "#1D4ED8",
    fontWeight: "700",
    fontSize: 12,
  },
  infoCard: {
    backgroundColor: "#F7FAFF",
    borderWidth: 1,
    borderColor: "#D6E2F5",
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    shadowColor: "#2563EB",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    marginBottom: SPACING.sm,
    color: "#173A6B",
  },
  sectionText: {
    color: "#496C97",
    lineHeight: 20,
  },
  infoLabel: {
    marginTop: 2,
    marginBottom: 6,
    color: "#2A4E81",
    fontWeight: "700",
    fontSize: 13,
  },
  infoDivider: {
    marginVertical: 12,
    height: 1,
    backgroundColor: "#D5E4FF",
  },
  primaryButton: {
    marginTop: 2,
    backgroundColor: "#2563EB",
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    alignItems: "center",
    shadowColor: "#2563EB",
    shadowOpacity: 0.24,
    shadowRadius: 14,
    elevation: 5,
  },
  primaryButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  logoutCard: {
    backgroundColor: "#F8E6E8",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E7BFC5",
    shadowColor: "#BE123C",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  logoutRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  logoutTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#B42318",
  },
  logoutText: {
    marginTop: 5,
    color: "#7A4950",
  },
});
