import { StyleSheet } from "react-native";
import { RADIUS, SPACING } from "../theme";

export const profesionalTrabajosStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#EAF2FF",
    padding: SPACING.lg,
    paddingTop: 30,
  },
  loader: {
    flex: 1,
    justifyContent: "center",
  },
  filtersRow: {
    alignItems: "center",
    paddingRight: SPACING.sm,
  },
  pill: {
    alignSelf: "flex-start",
    minHeight: 38,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#BED4FA",
    backgroundColor: "#E9F1FF",
    marginRight: SPACING.sm,
    justifyContent: "center",
  },
  pillActive: {
    backgroundColor: "#2563EB",
    borderColor: "#2563EB",
  },
  pillText: {
    fontWeight: "700",
    fontSize: 13,
    color: "#245CB8",
  },
  pillTextActive: {
    color: "#FFFFFF",
  },
  card: {
    backgroundColor: "#F7FAFF",
    padding: SPACING.lg,
    borderRadius: RADIUS.md,
    marginBottom: SPACING.md,
    borderWidth: 1,
    borderColor: "#D6E2F5",
    shadowColor: "#2563EB",
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
  },
  cardHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
  },
  cardTags: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 6,
  },
  titulo: {
    fontSize: 16,
    fontWeight: "800",
    flex: 1,
    color: "#0F2A52",
  },
  categoria: {
    marginTop: 6,
    color: "#2D5487",
    fontWeight: "700",
  },
  descripcion: {
    marginTop: 6,
    color: "#375B88",
    lineHeight: 20,
  },
  direccion: {
    marginTop: 10,
    color: "#4D6F99",
    fontWeight: "600",
  },
  metaWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  metaPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#E6F0FF",
    borderColor: "#C6DBFF",
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  metaPillText: {
    color: "#1E3A8A",
    fontWeight: "700",
    fontSize: 12,
  },
  list: {
    flex: 1,
  },
  listContent: {
    paddingBottom: SPACING.lg,
  },
  headerBlock: {
    marginBottom: SPACING.md,
  },
  heroCard: {
    backgroundColor: "#C7DBFF",
    borderColor: "#AFC9F9",
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
    marginBottom: SPACING.md,
  },
  heroKicker: {
    fontSize: 11,
    fontWeight: "800",
    color: "#27538D",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  heroTitle: {
    marginTop: 4,
    fontSize: 22,
    fontWeight: "800",
    color: "#0F2A52",
  },
  heroSubtitle: {
    marginTop: 6,
    color: "#365D8F",
    lineHeight: 19,
  },
  heroMeta: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-start",
    backgroundColor: "#EDF5FF",
    borderWidth: 1,
    borderColor: "#C8DCFF",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  heroMetaText: {
    color: "#1D4ED8",
    fontWeight: "700",
    fontSize: 12,
  },
  budgetBlock: {
    backgroundColor: "#F8FBFF",
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    marginTop: SPACING.sm,
    borderWidth: 1,
    borderColor: "#D2E4FF",
  },
  budgetHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  budgetTitle: {
    fontWeight: "700",
    color: "#1D4ED8",
  },
  budgetText: {
    marginTop: 4,
    color: "#365D8F",
    fontWeight: "600",
  },
  sliderTrack: {
    height: 8,
    borderRadius: 6,
    backgroundColor: "#D7E7FF",
    marginTop: SPACING.md,
    justifyContent: "center",
  },
  sliderLabel: {
    marginTop: SPACING.md,
    color: "#486A96",
    fontSize: 12,
    fontWeight: "600",
  },
  thumb: {
    position: "absolute",
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#2563EB",
    top: -6,
  },
  badgeUrgente: {
    marginTop: 2,
    alignSelf: "flex-start",
    backgroundColor: "#EF4444",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  badgeText: {
    color: "#fff",
    fontWeight: "600",
  },
  badgeCategoria: {
    marginTop: 2,
    alignSelf: "flex-start",
    backgroundColor: "#E0ECFF",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#C2D6FF",
  },
  badgeCategoriaText: {
    color: "#1E3A8A",
    fontWeight: "700",
    fontSize: 11,
  },
  specialtyFilterBlock: {
    backgroundColor: "#F8FBFF",
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    marginTop: SPACING.sm,
    borderWidth: 1,
    borderColor: "#D2E4FF",
  },
  specialtyWrap: {
    marginTop: SPACING.sm,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  specialtyChip: {
    borderWidth: 1,
    borderColor: "#BED4FA",
    backgroundColor: "#E9F1FF",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  specialtyChipActive: {
    backgroundColor: "#2563EB",
    borderColor: "#2563EB",
  },
  specialtyChipText: {
    color: "#245CB8",
    fontWeight: "700",
    fontSize: 12,
  },
  specialtyChipTextActive: {
    color: "#fff",
  },
  specialtyEmptyText: {
    marginTop: SPACING.sm,
    color: "#4B6E98",
    fontWeight: "600",
  },
  emptyContainer: {
    marginTop: 28,
    alignItems: "center",
  },
  emptyTitle: {
    fontWeight: "700",
    fontSize: 16,
  },
  emptyText: {
    marginTop: 6,
    color: "#365D8F",
    textAlign: "center",
  },
  warningCard: {
    backgroundColor: "#FFECCF",
    borderColor: "#F59E0B",
    borderWidth: 1,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    marginBottom: SPACING.md,
  },
  warningTitle: {
    color: "#92400E",
    fontWeight: "700",
  },
  warningText: {
    color: "#B45309",
    marginTop: 4,
  },
});
