import { StyleSheet } from "react-native";

export const profesionalDashboardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#EAF2FF",
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 30,
    paddingBottom: 40,
    gap: 18,
  },
  header: {
    marginBottom: 2,
    backgroundColor: "#C7DBFF",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#AFC9F9",
  },
  headerKicker: {
    fontSize: 12,
    fontWeight: "700",
    color: "#27538D",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  headerTitle: {
    marginTop: 6,
    fontSize: 26,
    fontWeight: "800",
    color: "#0F2A52",
  },
  headerSubtitle: {
    marginTop: 6,
    color: "#3D628F",
    lineHeight: 20,
  },
  summaryCard: {
    backgroundColor: "#DCEBFF",
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#BFD8FF",
    shadowColor: "#2563EB",
    shadowOpacity: 0.16,
    shadowRadius: 16,
    elevation: 4,
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#1E3A8A",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 10,
  },
  titleIcon: {
    marginTop: 1,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#334155",
    marginBottom: 10,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  summaryRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  summaryItem: {
    flex: 1,
  },
  summaryLabel: {
    color: "#4C6FA5",
    fontSize: 12,
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    fontWeight: "600",
  },
  summaryValue: {
    fontSize: 26,
    fontWeight: "800",
    color: "#10386E",
  },
  activityCard: {
    backgroundColor: "#D6F5E8",
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "#AEE3CD",
    shadowColor: "#059669",
    shadowOpacity: 0.14,
    shadowRadius: 14,
    elevation: 4,
  },
  activityRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  activityItem: {
    flex: 1,
  },
  activityNumber: {
    fontSize: 24,
    fontWeight: "800",
    color: "#0E7A56",
  },
  activityLabel: {
    marginTop: 4,
    fontSize: 13,
    color: "#4B7C6A",
    fontWeight: "600",
  },
  divider: {
    width: 1,
    height: 42,
    backgroundColor: "#D7E4F8",
    marginHorizontal: 10,
  },
  warningCard: {
    backgroundColor: "#FFEBC7",
    borderColor: "#F59E0B",
    borderWidth: 1,
    borderRadius: 14,
    padding: 14,
    shadowColor: "#F59E0B",
    shadowOpacity: 0.13,
    shadowRadius: 12,
    elevation: 3,
  },
  warningTitle: {
    color: "#92400E",
    fontWeight: "700",
  },
  warningText: {
    color: "#B45309",
    marginTop: 4,
  },
  ctaMain: {
    backgroundColor: "#2563EB",
    borderRadius: 18,
    paddingHorizontal: 20,
    paddingVertical: 20,
    shadowColor: "#2563EB",
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 8,
  },
  ctaMainTitle: {
    color: "#FFFFFF",
    fontSize: 19,
    fontWeight: "700",
  },
  ctaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  ctaMainText: {
    marginTop: 7,
    color: "#DBEAFE",
    fontSize: 14,
  },
  grid: {
    flexDirection: "row",
    gap: 12,
  },
  quickCard: {
    flex: 1,
    borderRadius: 16,
    padding: 16,
    minHeight: 110,
    borderWidth: 1,
    shadowColor: "#0F172A",
    shadowOpacity: 0.14,
    shadowRadius: 12,
    elevation: 4,
  },
  quickCardSky: {
    backgroundColor: "#CFE2FF",
    borderColor: "#AFCBFF",
  },
  quickCardMint: {
    backgroundColor: "#CFF2E2",
    borderColor: "#A8E2C9",
  },
  quickTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: "#10386E",
  },
  quickTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  quickText: {
    marginTop: 6,
    color: "#365D8F",
    lineHeight: 19,
  },
  logoutCard: {
    backgroundColor: "#F8E6E8",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E7BFC5",
    shadowColor: "#BE123C",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  logoutTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#B42318",
  },
  logoutRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  logoutText: {
    marginTop: 5,
    color: "#7A4950",
  },
  logoutLink: {
    marginTop: 12,
    alignItems: "center",
  },
  logoutLinkText: {
    color: "#B42318",
    fontWeight: "700",
  },
});
