import { StyleSheet } from "react-native";
import { RADIUS, SPACING } from "../theme";

export const trabajoDetalleStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#EAF2FF",
  },
  content: {
    paddingHorizontal: SPACING.lg,
    paddingTop: 30,
    paddingBottom: 40,
    gap: SPACING.md,
  },
  heroCard: {
    backgroundColor: "#DCEBFF",
    borderColor: "#BED5FF",
    borderWidth: 1,
    borderRadius: 16,
    padding: SPACING.md,
  },
  heroKicker: {
    fontSize: 11,
    fontWeight: "800",
    color: "#27538D",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  titulo: {
    marginTop: 4,
    fontSize: 22,
    fontWeight: "800",
    color: "#0F2A52",
  },
  descripcion: {
    marginTop: 8,
    color: "#365D8F",
    lineHeight: 19,
  },
  locationText: {
    marginTop: 8,
    color: "#3D628F",
    fontWeight: "600",
  },
  heroMetaRow: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  estadoBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  estadoBadgeText: {
    fontSize: 11,
    fontWeight: "800",
  },
  rangeBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: "#E6F0FF",
    borderWidth: 1,
    borderColor: "#C6DBFF",
  },
  rangeBadgeText: {
    color: "#1E3A8A",
    fontWeight: "800",
    fontSize: 11,
  },
  urgenteBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: "#FEE2E2",
  },
  urgenteBadgeText: {
    color: "#B91C1C",
    fontWeight: "800",
    fontSize: 11,
  },
  sectionCard: {
    backgroundColor: "#F7FAFF",
    borderColor: "#D6E2F5",
    borderWidth: 1,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    shadowColor: "#2563EB",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  sectionTitle: {
    color: "#173A6B",
    fontWeight: "800",
    fontSize: 16,
    marginBottom: SPACING.sm,
  },
  emptyText: {
    color: "#4B6E98",
    fontWeight: "600",
  },
  offerCard: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#D8E6FF",
    borderRadius: 12,
    padding: 12,
    marginTop: 10,
  },
  offerTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  offerName: {
    color: "#1E3A8A",
    fontWeight: "700",
    flex: 1,
  },
  offerAmount: {
    color: "#0F2A52",
    fontWeight: "800",
    fontSize: 18,
  },
  offerUrgentTotal: {
    marginTop: 4,
    color: "#B45309",
    fontWeight: "700",
  },
  offerRating: {
    marginTop: 6,
    color: "#3D628F",
    fontWeight: "600",
  },
  offerComment: {
    marginTop: 4,
    color: "#5A769B",
    fontStyle: "italic",
  },
  primaryButton: {
    marginTop: 12,
    backgroundColor: "#2563EB",
    paddingVertical: 10,
    borderRadius: RADIUS.md,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  secondaryButton: {
    marginTop: 8,
    backgroundColor: "#E6F0FF",
    borderColor: "#C6DBFF",
    borderWidth: 1,
    paddingVertical: 10,
    borderRadius: RADIUS.md,
    alignItems: "center",
  },
  secondaryButtonText: {
    color: "#1E3A8A",
    fontWeight: "700",
  },
  ratingRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  starChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "#FFF7ED",
    borderWidth: 1,
    borderColor: "#FED7AA",
  },
  starChipActive: {
    backgroundColor: "#F59E0B",
    borderColor: "#F59E0B",
  },
  starChipText: {
    color: "#9A3412",
    fontWeight: "700",
  },
  starChipTextActive: {
    color: "#FFFFFF",
  },
  input: {
    borderWidth: 1,
    borderColor: "#C8DAF6",
    borderRadius: RADIUS.md,
    padding: SPACING.sm,
    backgroundColor: "#ECF4FF",
    color: "#0F2A52",
    minHeight: 44,
    textAlignVertical: "top",
  },
});
